spring.application.name=aceites

spring.datasource.url=jdbc:postgresql://dpg-d7tahbq8qa3s73ea3970-a.oregon-postgres.render.com:5432/inventario_1unz?sslmode=require

spring.datasource.username=alexein

spring.datasource.password=8rlTe4dyTAsYGc8U9JARs9YC0vjx1M5C

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
server.address=0.0.0.0
